author:
  email: ludeeus@gmail.com
  homepage: https://github.com/ludeeus
  name: ludeeus
description: Blueprint for custom_component developers.
files:
- custom_components/blueprint/__init__.py
- custom_components/blueprint/binary_sensor.py
- custom_components/blueprint/const.py
- custom_components/blueprint/sensor.py
keywords:
- blueprint
- homeassistant
- home-assistant
- custom-component
- python
license: MIT License
name: blueprint
type: component
