name: Cron actions

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    name: Validate with hassfest
    steps:
        - uses: "actions/checkout@v2"
        - uses: "home-assistant/actions/hassfest@master"